### ISSUE TITLE
Blog thumbnails appear cropped

### ISSUE THREAD

**Issue by kartikcho** [InternetFreedomFoundation/DPDC-theme#26]
Thumbnails on the blog page appear cropped. This could be a simple fix by increasing img width

![image](https://user-images.githubusercontent.com/48270786/166961162-8d82e045-e78a-4d33-93bc-528ec1edf334.png)

**Comment by krishna-acondy** [comment]
It's an even simpler fix if you use `object-fit: contain` instead of `cover`.
